<h1>Novo Livro</h1>

<?php 

$form = $this->form; 

$form->setAttribute('action', $this->url('livraria-admin', array('controller' => 'livros', 'action' => 'add')));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('categoria'));
echo $this->formRow($form->get('autor'));
echo $this->formRow($form->get('isbn'));
echo $this->formRow($form->get('valor')) . "<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>